### ISSUE TITLE
Test InvoiceDemo in all editions of Starcounter

### ISSUE THREAD

**Issue by warpech** [Starcounter/InvoiceDemo#11]
Currently, InvoiceDemo (this repository) is only tested in Polyjuice edition. 

It should also be tested in Starcounter edition.

**Comment by k-rus** [comment]
> It should also be tested in Starcounter edition.

Actually, we have report that InvoiceDemo does not work in Starcounter edition. If I remember @alexanderstc reported a weaver error.

**Comment by parherman** [comment]
This issue is depends/involves issue #12, Starcounter issue [#2703 - Polyjuice installation and Starcounter installation must be equal](https://github.com/Starcounter/Starcounter/issues/2703) and it would be really good if Starcounter issue [#2609 - Add cli/no gui option to the installer](https://github.com/Starcounter/Starcounter/issues/2609) was completed for this

**Comment by parherman** [comment]
We could add a simpler test that just clones the InvoiceDemo repo and runs it with star for now, @warpech should both solutions run on both editions?

**Comment by warpech** [comment]
Yes, the current code (InvoiceDemo1.sln, InvoiceDemo2.sln) should work on both solutions.

It would be great to test live repo code in the test suite for both Polyjuice and Starcounter edition.

**Comment by warpech** [comment]
This is dependent on https://github.com/Starcounter/InvoiceDemo/issues/20

**Comment by warpech** [comment]
This is outdated. Now InvoiceDemo is tested in Starcounter develop nightly.
